import { Outfit } from "next/font/google";
import "./globals.css";
import ClerkProvider from './services/clerk/components/ClerkProvider'
import { ThemeProvider } from 'next-themes'

const outfitSans = Outfit({
  variable: "--font-outfit-sans",
  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${outfitSans.variable} antialiased font-sans`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableColorScheme disableTransitionOnChange>
        {children}
        </ThemeProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
